defmodule AlexClawWeb.AdminLive.McpKeyPageTest do
  @moduledoc """
  Getting an MCP key (0.4.0 S3; decided 2026-09-25).

  The MCP key is generated by AlexClaw and recognised by its HMAC, never
  stored (mcp/key_test.exs). A person gets one on the Config page:
  - "Generate" needs the elevation; it shows the new key ONCE, in the reply
    to that action — never on a later render of the page;
  - the page otherwise says only whether a key is configured;
  - generating again replaces the key (the old one stops working);
  - "Revoke" needs the elevation and leaves no key;
  - without the elevation, both are refused and audited.
  Events: `generate_mcp_key`, `revoke_mcp_key` (group "mcp" holds them).
  """
  use AlexClawWeb.ConnCase, async: false
  @moduletag :integration
  @moduletag :vault

  import Ecto.Query

  alias AlexClaw.Auth.{AuditEntry, Elevation}
  alias AlexClaw.MCP.Key
  alias AlexClaw.Repo

  setup %{conn: conn} do
    sid = Elevation.new_sid()

    on_exit(fn ->
      AlexClaw.SandboxCleanup.run(fn -> Elevation.revoke(sid) end)
      Key.revoke()
    end)

    {:ok, conn: authenticate(conn, sid), sid: sid}
  end

  defp elevate(sid), do: {:ok, _} = Elevation.grant(sid)

  defp open_mcp(conn) do
    {:ok, view, _html} = live(conn, "/config")
    html = render_click(view, "toggle_group", %{"group" => "mcp"})
    {view, html}
  end

  # A generated key: the random part is long; pull the first long token
  # from the reply that shows it.
  defp shown_key(html) do
    case Regex.run(~r/data-mcp-key="([^"]{32,})"/, html) do
      [_, key] -> key
      nil -> nil
    end
  end

  defp denied? do
    Repo.exists?(from(e in AuditEntry, where: e.decision == "deny" and like(e.reason, "%mcp%")))
  end

  test "generate, with the elevation: the key is shown once and works", %{conn: conn, sid: sid} do
    elevate(sid)
    {view, _html} = open_mcp(conn)

    html = render_click(view, "generate_mcp_key", %{})
    key = shown_key(html)

    assert key, "the generated key was not shown (expected data-mcp-key)"
    assert Key.valid?(key)

    # Shown once: a fresh render of the page does not show it again.
    {_view2, later} = open_mcp(conn)
    refute later =~ key
    assert later =~ ~r/configured/i
  end

  test "generate without the elevation: refused, audited, no key", %{conn: conn} do
    {view, _html} = open_mcp(conn)

    html = render_click(view, "generate_mcp_key", %{})

    assert is_nil(shown_key(html))
    assert denied?()
  end

  test "generating again replaces the key", %{conn: conn, sid: sid} do
    elevate(sid)
    {view, _html} = open_mcp(conn)

    old = view |> render_click("generate_mcp_key", %{}) |> shown_key()
    new = view |> render_click("generate_mcp_key", %{}) |> shown_key()

    refute Key.valid?(old)
    assert Key.valid?(new)
  end

  test "revoke, with the elevation: no key works; without it: refused", %{conn: conn, sid: sid} do
    {:ok, key} = Key.generate()
    {view, _html} = open_mcp(conn)

    render_click(view, "revoke_mcp_key", %{})
    assert Key.valid?(key), "revoked without the elevation"
    assert denied?()

    elevate(sid)
    html = render_click(view, "revoke_mcp_key", %{})

    refute Key.valid?(key)
    assert html =~ ~r/not configured/i
  end
end
