defmodule Mix.Tasks.AlexClaw.ApiMap do
  @shortdoc "Writes local-docs/API_MAP.md: the public surface of every module in lib/"

  @moduledoc """
  Writes `local-docs/API_MAP.md`, a map of every module under `lib/`: the first
  line of its moduledoc, its public function heads with their specs, the
  behaviours it implements and which of their callbacks it defines, a
  LiveView's `handle_event` names, and an Ecto schema's fields and types. No
  function bodies.

  The file is local — `local-docs/` is not in the repository — and generated,
  never edited: regenerate it when the code changes.

      make api-map
  """
  use Mix.Task

  @path "local-docs/API_MAP.md"
  @requirements ["compile"]
  @live_behaviours [Phoenix.LiveView, Phoenix.LiveComponent]

  @impl Mix.Task
  def run(_args) do
    File.mkdir_p!(Path.dirname(@path))
    File.write!(@path, render())
    Mix.shell().info("Wrote #{@path}")
  end

  @doc "Where the map is written."
  @spec path() :: String.t()
  def path, do: @path

  @doc "The map, exactly as `run/1` writes it."
  @spec render() :: String.t()
  def render do
    IO.iodata_to_binary([
      "# API map\n\n",
      "Generated by `mix alex_claw.api_map` from the compiled modules in `lib/`, ",
      "at commit `#{commit()}`#{lib_changes()}, version `#{version()}`. ",
      "Do not edit; regenerate with `make api-map`.\n\n",
      Enum.map(lib_modules(), &module_section/1)
    ])
  end

  defp version, do: :alex_claw |> Application.spec(:vsn) |> to_string()

  # Read from git where the map is generated; "unknown" when git or the
  # repository is not there. safe.directory: in a container the checkout is
  # owned by another user, and git refuses it otherwise.
  defp commit, do: git(["rev-parse", "--short", "HEAD"], "unknown")

  # The map is built from the working tree, which may be ahead of the commit.
  defp lib_changes do
    case git(["status", "--porcelain", "--", "lib"], "") do
      "" -> ""
      _changed -> " plus uncommitted changes in `lib/`"
    end
  end

  defp git(args, fallback) do
    case System.cmd("git", ["-c", "safe.directory=*" | args], stderr_to_stdout: true) do
      {out, 0} -> String.trim(out)
      _failed -> fallback
    end
  rescue
    ErlangError -> fallback
  end

  # Test support is compiled into the app in the test env; only lib/ is mapped.
  defp lib_modules do
    {:ok, modules} = :application.get_key(:alex_claw, :modules)

    modules
    |> Enum.map(&{&1, source(&1)})
    |> Enum.filter(fn {_module, source} -> String.starts_with?(source, "lib/") end)
    |> Enum.sort()
  end

  defp source(module) do
    Code.ensure_loaded!(module)

    module.module_info(:compile)
    |> Keyword.get(:source, ~c"")
    |> to_string()
    |> Path.relative_to(File.cwd!())
  end

  defp module_section({module, source}) do
    {moduledoc, entries} = docs(module)

    [
      "## ",
      inspect(module),
      "\n\n`",
      source,
      "`",
      first_line(moduledoc),
      "\n\n",
      behaviours(module),
      schema(module),
      events(module, source),
      functions(module, entries)
    ]
  end

  defp docs(module) do
    case Code.fetch_docs(module) do
      {:docs_v1, _anno, _lang, _format, moduledoc, _meta, entries} -> {moduledoc, entries}
      _no_docs -> {:none, []}
    end
  end

  defp first_line(%{"en" => text}) do
    text
    |> String.split("\n", trim: true)
    |> List.first("")
    |> String.trim()
    |> then(&(" — " <> &1))
  end

  defp first_line(_hidden_or_none), do: ""

  # --- Behaviours: each one, with the callbacks this module defines ---

  defp behaviours(module) do
    module.module_info(:attributes)
    |> Keyword.get_values(:behaviour)
    |> List.flatten()
    |> Enum.uniq()
    |> Enum.sort()
    |> section("Behaviours", &behaviour_line(module, &1))
  end

  defp behaviour_line(module, behaviour) do
    implemented =
      behaviour
      |> callbacks()
      |> Enum.filter(fn {name, arity} -> function_exported?(module, name, arity) end)
      |> Enum.map_join(", ", fn {name, arity} -> "#{name}/#{arity}" end)

    "- `#{inspect(behaviour)}`: #{implemented}\n"
  end

  defp callbacks(behaviour) do
    Code.ensure_loaded(behaviour)
    callbacks_of(behaviour, function_exported?(behaviour, :behaviour_info, 1))
  end

  defp callbacks_of(behaviour, true), do: behaviour.behaviour_info(:callbacks) |> Enum.sort()
  defp callbacks_of(_behaviour, false), do: []

  # --- Ecto schemas: source table, then each field and its type ---

  defp schema(module) do
    schema_of(module, function_exported?(module, :__schema__, 1))
  end

  defp schema_of(module, true) do
    table = module.__schema__(:source) || "embedded"

    module.__schema__(:fields)
    |> Enum.map(&"- `#{&1}`: `#{inspect(module.__schema__(:type, &1))}`\n")
    |> section("Schema (#{table})", & &1)
  end

  defp schema_of(_module, false), do: []

  # --- LiveView events, read from the source: clause patterns are not in docs ---

  defp events(module, source) do
    live? = Enum.any?(@live_behaviours, &(&1 in behaviour_list(module)))
    events_of(live?, source)
  end

  defp behaviour_list(module),
    do: module.module_info(:attributes) |> Keyword.get_values(:behaviour) |> List.flatten()

  defp events_of(false, _source), do: []

  defp events_of(true, source) do
    {_ast, names} =
      source
      |> File.read!()
      |> Code.string_to_quoted!()
      |> Macro.prewalk([], &collect_event/2)

    names
    |> Enum.uniq()
    |> Enum.sort()
    |> Enum.map(&"- `#{&1}`\n")
    |> section("handle_event", & &1)
  end

  defp collect_event({:def, _, [{:when, _, [head, _guard]} | _]} = node, names),
    do: {node, event_name(head, names)}

  defp collect_event({:def, _, [head | _]} = node, names), do: {node, event_name(head, names)}
  defp collect_event(node, names), do: {node, names}

  defp event_name({:handle_event, _, [name | _]}, names) when is_binary(name), do: [name | names]
  defp event_name(_head, names), do: names

  # --- Public functions: the head from the docs, the spec beneath it ---

  defp functions(module, entries) do
    specs = specs(module)

    entries
    |> Enum.filter(&public_function?/1)
    |> Enum.sort_by(fn {{_kind, name, arity}, _, _, _, _} -> {name, arity} end)
    |> Enum.map(&function_lines(&1, specs))
    |> section("Functions", & &1)
  end

  defp public_function?({{kind, name, _arity}, _, _, _, _}),
    do: kind in [:function, :macro] and not String.starts_with?(Atom.to_string(name), "__")

  defp function_lines({{_kind, name, arity}, _anno, signature, _doc, _meta}, specs) do
    head = List.first(signature) || "#{name}/#{arity}"
    spec_lines = specs |> Map.get({name, arity}, []) |> Enum.map(&"  `@spec #{&1}`\n")
    ["- `", head, "`\n" | spec_lines]
  end

  defp specs(module) do
    case Code.Typespec.fetch_specs(module) do
      {:ok, specs} -> Map.new(specs, &rendered_spec/1)
      :error -> %{}
    end
  end

  defp rendered_spec({{name, arity}, clauses}) do
    {{name, arity}, Enum.map(clauses, &spec_string(name, &1))}
  end

  defp spec_string(name, clause),
    do: name |> Code.Typespec.spec_to_quoted(clause) |> Macro.to_string()

  defp section([], _title, _render), do: []
  defp section(items, title, render), do: ["**", title, "**\n\n", Enum.map(items, render), "\n"]
end
