defmodule AlexClawWeb.AdminLive.Config.McpKeyPanel do
  @moduledoc """
  The MCP key on the Config page (group "mcp").

  The key is generated by AlexClaw and recognised by its fingerprint, never
  stored (`AlexClaw.MCP.Key`), so the page cannot show it later: "Generate"
  shows the new key once, in the reply to that action, until it is dismissed;
  otherwise the page says only whether a key is configured. "Generate" and
  "Revoke" need the elevation, like any other change on the page.
  """
  use Phoenix.Component

  alias AlexClaw.MCP.Key
  alias AlexClawWeb.Live.Elevation

  @setting "mcp.api_key"

  @doc "Whether an MCP key is configured."
  @spec configured?() :: boolean()
  def configured?, do: AlexClaw.Config.secret_set?(@setting)

  @doc "Generate a new key (replacing any old one), behind the elevation, and show it."
  @spec generate(Phoenix.LiveView.Socket.t()) :: {:noreply, Phoenix.LiveView.Socket.t()}
  def generate(socket) do
    Elevation.gated(socket, "#{@setting}: generated",
      write: &Key.generate/0,
      ok: fn socket, key ->
        socket
        |> Phoenix.LiveView.put_flash(:info, "MCP key generated. Copy it now: it is shown once.")
        |> assign(mcp_key_configured: true, new_mcp_key: key)
      end
    )
  end

  @doc "Revoke the key, behind the elevation: MCP then refuses every request."
  @spec revoke(Phoenix.LiveView.Socket.t()) :: {:noreply, Phoenix.LiveView.Socket.t()}
  def revoke(socket) do
    Elevation.gated(socket, "#{@setting}: revoked",
      write: fn -> with :ok <- Key.revoke(), do: {:ok, :revoked} end,
      ok: fn socket, :revoked ->
        socket
        |> Phoenix.LiveView.put_flash(:info, "MCP key revoked")
        |> assign(mcp_key_configured: false, new_mcp_key: nil)
      end
    )
  end

  attr(:configured, :boolean, required: true)
  attr(:new_key, :string, default: nil)

  @doc "The panel: the key's state, the newly generated key if any, and the actions."
  @spec panel(map()) :: Phoenix.LiveView.Rendered.t()
  def panel(assigns) do
    ~H"""
    <div class="border-t border-gray-800 px-4 py-3 space-y-3">
      <div class="flex items-center justify-between">
        <div class="text-sm text-gray-300">
          MCP key: <span class="font-semibold">{if @configured, do: "configured", else: "not configured"}</span>
        </div>
        <div class="flex gap-2">
          <button phx-click="generate_mcp_key"
            class="px-3 py-1 text-xs rounded bg-blue-700 hover:bg-blue-600 text-white">
            {if @configured, do: "Generate a new key", else: "Generate"}
          </button>
          <button :if={@configured} phx-click="revoke_mcp_key"
            data-confirm="Revoke the MCP key? Every MCP client stops working."
            class="px-3 py-1 text-xs rounded bg-red-800 hover:bg-red-700 text-white">
            Revoke
          </button>
        </div>
      </div>
      <div :if={@new_key} class="rounded border border-yellow-700 bg-yellow-950 p-3 space-y-2">
        <div class="text-xs text-yellow-300">
          The new key, shown this once. It is not stored and cannot be shown again.
        </div>
        <code data-mcp-key={@new_key} class="block break-all text-sm text-white select-all">{@new_key}</code>
        <button phx-click="dismiss_mcp_key" class="px-3 py-1 text-xs rounded bg-gray-700 hover:bg-gray-600 text-white">
          Done
        </button>
      </div>
    </div>
    """
  end
end
